export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ATTENDANCE = "GET_ATTENDANCE";
export const GET_USERS = "GET_USERS";
export const GET_ATTENDANCE_RESPONSE = "GET_ATTENDANCE_RESPONSE";